### ISSUE TITLE
Ruby scripting error, after clicking the ruby script icon

### ISSUE THREAD

**Issue by askumar** [twineworks/ruby-for-pentaho-kettle#23]
Hi, I am getting this error, after clicking the ruby icon i get this message. can you please point me to right direction, what is the problem. 
java.lang.NullPointerException
    at org.jruby.embed.internal.SingleThreadLocalContextProvider.getRuntime(SingleThreadLocalContextProvider.java:61)
    at org.typeexit.kettle.plugin.steps.ruby.RubyStepSyntaxHighlighter.<init>(RubyStepSyntaxHighlighter.java:115)
    at org.typeexit.kettle.plugin.steps.ruby.RubyStepDialog.open(RubyStepDialog.java:233)
    at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:136)
    at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:7835)
    at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:2749)
    at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:705)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:195)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4128)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1457)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1480)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1465)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1270)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3974)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3613)
    at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1221)
    at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7044)
    at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:8304)
    at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:580)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.pentaho.commons.launcher.Launcher.main(Launcher.java:134)

Thanks

**Comment by msunilgupta** [comment]
Hi Brandon Rice/slawo-ch,

I had downloaded & installed the latest version of "Ruby-Scripting-for-Kettle-master" from your github. But still I am facing the same error "org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta"
org.pentaho.di.core.exception.KettlePluginException: 
Class not found
org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta

	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:471)
	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:336)
	at org.pentaho.di.ui.spoon.Spoon.newStep(Spoon.java:6598)
	at org.pentaho.di.ui.spoon.trans.TransGraph$5.drop(TransGraph.java:613)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.dnd.DropTarget.Drop(Unknown Source)
	at org.eclipse.swt.dnd.DropTarget.Drop_64(Unknown Source)
	at org.eclipse.swt.dnd.DropTarget$3.method6(Unknown Source)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(Unknown Source)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(Unknown Source)
	at org.eclipse.swt.dnd.DragSource.access$000(Unknown Source)
	at org.eclipse.swt.dnd.DragSource$1.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1310)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7931)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9202)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:648)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:87)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:466)
	... 30 more

My Setup details:-
- Pentaho version - 5.2(pdi-ce-5.2.0.0-209.zip) on Windows-8.1 OS
- JAVA JDK 1.7
Please let me know how to proceed further for fixing the issue.

**Comment by nevern02** [comment]
I haven't tested this plugin against Kettle 5.x.  We stopped using it at work, so I haven't had a reason to keep up on it.  I can only theorize about what your problem might be, unfortunately.  Are you getting this error inside Kettle when trying to run an actual transformation that contains a Ruby step?  Or are you unable to start Kettle at all once the plugin is installed?

**Comment by msunilgupta** [comment]
Hi Brandon Rice,

Yes I am getting this error inside Kettle when try to add Ruby Step with in a transformation.
Could you please suggest how to proceed further for running a Ruby script using kettle 5.0

Thanks,
Sunil gupta M

**Comment by slawo-ch** [comment]
Using JRuby's global runtime now
