### ISSUE TITLE
Ruby scripting error "org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta", after clicking the ruby script icon

### ISSUE THREAD

**Issue by msunilgupta** [twineworks/ruby-for-pentaho-kettle#25]
Hi Slawo-ch,

I had downloaded & installed the latest version of "Ruby-Scripting-for-Kettle-master" from your github. But still I am facing the same error "org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta"
org.pentaho.di.core.exception.KettlePluginException: 
Class not found
org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta
at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:471)
at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:336)
at org.pentaho.di.ui.spoon.Spoon.newStep(Spoon.java:6598)
at org.pentaho.di.ui.spoon.trans.TransGraph$5.drop(TransGraph.java:613)
at org.eclipse.swt.dnd.DNDListener.handleEvent(Unknown Source)
at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
at org.eclipse.swt.dnd.DropTarget.Drop(Unknown Source)
at org.eclipse.swt.dnd.DropTarget.Drop_64(Unknown Source)
at org.eclipse.swt.dnd.DropTarget$3.method6(Unknown Source)
at org.eclipse.swt.internal.ole.win32.COMObject.callback6(Unknown Source)
at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
at org.eclipse.swt.dnd.DragSource.drag(Unknown Source)
at org.eclipse.swt.dnd.DragSource.access$000(Unknown Source)
at org.eclipse.swt.dnd.DragSource$1.handleEvent(Unknown Source)
at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1310)
at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7931)
at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9202)
at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:648)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.typeexit.kettle.plugin.steps.ruby.RubyStepMeta
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:87)
at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:106)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:466)
... 30 more

My Setup details:-
Pentaho version - 5.2(pdi-ce-5.2.0.0-209.zip) on Windows-8.1 OS
JAVA JDK 1.7 Please let me know how to proceed further for fixing the issue.

Let me know how to proceed further.

Thanks,
Sunil gupta M

**Comment by slawo-ch** [comment]
Installation procedure has changed. You can run `mvn package` to create a plugin zip in `./target`, and unzip it into `data-integration/plugins`.
